swagger: "2.0"

info:
  title: Network API Endpoint
  version: "1.0"

basePath: /api/network

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header


paths:
  /internet/check:
    get:
      summary: Pings the internet and returns the response.
      operationId: src.api.network.internet.check
      responses:
        200:
          description: Successfully connected to the internet.
          schema:
            $ref: '#/definitions/Json'
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'

  /internet/restart:
    get:
      summary: Restarts the network interface and returns the resulting IP.
      operationId: src.api.network.internet.restart
      responses:
        200:
          description: Successfully restarted the network interface.
          schema:
            $ref: '#/definitions/Json'
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'

  /vpn/check:
    get:
      summary: Pings the an internal VPN address and returns the response.
      operationId: src.api.network.vpn.check
      responses:
        200:
          description: Successfully connected to the VPN network.
          schema:
            $ref: '#/definitions/Json'
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'

  /vpn/restart:
    get:
      summary: Restarts the systems VPN daemon and returns the resulting IP.
      operationId: src.api.network.vpn.restart
      responses:
        200:
          description: Successfully restarted the VPN daemon.
          schema:
            $ref: '#/definitions/Json'
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'


definitions:
  Json:
    type: object
    properties:
      json:
        type: string
        description: Resulting json object.

  CommandException:
    type: object
    properties:
      json:
        type: string
        description: The return code and error output.
