sudo: true

language: python

python: 3.6

os: linux

cache: pip

notifications:
  email: false

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false
  - deploy

jobs:
  include:
    - stage: test
      install: pip install nose
      script: nosetests

    - stage: release
      install: pip install python-semantic-release
      script: .travis/release.sh

    - stage: deploy
      script: .travis/deploy.sh
