sudo: true

language: python

python: 3.6

os: linux

cache: pip

stages:
  - test
  - name: deploy
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: test
      install: pip install nose
      script: nosetests

    - stage: deploy
      install: pip install python-semantic-release
      script:
       - .travis/deploy.sh
       - .travis/webhook.sh
