sudo: false

language:
  - python
  - node_js

python: 3.6
node_js: 10

os: linux

cache: pip

notifications:
  email: false

stages:
#  - test
  - name: release
    if: branch = master AND type = push AND fork = false
  - deploy

jobs:
  include:
#    - stage: test
#      install: pip install -r requirements/dev.txt
#      script: nosetests

    - stage: release
      script: .travis/release.sh

    - stage: deploy
      script: .travis/deploy.sh
