matrix:
    include:
        - language: python
            python: 3.6
            before_script:
                - cd tests
            script:
                - python -m unittest discover

        - language: python
            python: 2.7
            before_script:
                - cd tests
            script:
                - python -m unittest discover

notifications:
    email:
        recipients:
            - 265815F@curtin.edu.au
        on_success: never
        on_failure: always
