sudo: false

language: python

python:
  - 3.6

os:
  - linux

cache: pip

notifications:
  email: false

stages:
  # - test
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    # - stage: test
      # script: 

    - stage: release
	  python: 3.6
      deploy:
        provider: script
        skip_cleanup: true
        script: bash scripts/deploy.sh
