sudo: false

language: python

python:
  - 3.6

os:
  - linux

cache: pip

notifications:
  email: false

stages:
  - lint
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: lint
      install: "pip install nose pylint"
      script: "nosetests && pylint --errors-only"

    - stage: release
	  python: 3.6
      deploy:
        provider: script
        skip_cleanup: true
        script: bash scripts/deploy.sh
