swagger: "2.0"

info:
  title: Session API Endpoint
  version: "1.0"

basePath: /api/session

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header


paths:
  /check:
    get:
      summary: Checks that a given token is valid.
      operationId: src.api.session.endpoints.check_token
      responses:
        200:
          description: Token is valid.

  /hostname:
    get:
      summary: Gets the systems hostname.
      operationId: src.api.session.endpoints.hostname
      responses:
        200:
          description: Successfully gathered machines hostname.
          schema:
            $ref: '#/definitions/Json'
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'


definitions:
  Json:
    type: object
    properties:
      json:
        type: string
        description: Resulting json object.

  CommandException:
    type: object
    properties:
      json:
        type: string
        description: The return code and error output.

