swagger: "2.0"

info:
  title: Session API Endpoint
  version: "1.0"

basePath: /api/session

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header


paths:
  /auth:
    post:
      summary: Logs the user in and returns JWT access and refresh tokens.
      operationId: src.api.session.token.auth
      parameters:
        - name: json
          in: body
          schema:
            $ref: '#/definitions/Json'
      responses:
        200:
          description: Successfully logged in.
          schema:
            $ref: '#/definitions/Json'
        401:
          description: Bad username or password.
          schema:
            $ref: '#/definitions/Json'
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'

  /check:
    get:
      summary: Use on page navigation, disk_partitions access token validity.
      operationId: src.api.session.token.check
      responses:
        200:
          description: Successfully checked the access token.

  /refresh:
    get:
      summary: Using the provided refresh token, returns a new access token.
      operationId: src.api.session.token.refresh
      responses:
        200:
          description: Successfully refreshed the access token.
          schema:
            $ref: '#/definitions/Json'

  /hostname:
    get:
      summary: Gets the systems hostname.
      operationId: src.api.session.hostname.get
      responses:
        200:
          description: Successfully gathered machines hostname.
          schema:
            $ref: '#/definitions/Json'
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'


definitions:
  Json:
    type: object
    properties:
      json:
        type: string
        description: Resulting json object.

  CommandException:
    type: object
    properties:
      json:
        type: string
        description: The return code and error output.

