swagger: "2.0"

info:
  title: Storage API Endpoint
  version: "1.0"

basePath: /api/storage

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header


paths:
  /check:
    get:
      summary: Checks and returns the systems partitions disk usage.
      operationId: src.api.storage.check.check
      responses:
        200:
          description: Successfully gathered the disk usage.
          schema:
            $ref: '#/definitions/Json'
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'


definitions:
  Json:
    type: object
    properties:
      json:
        type: string
        description: Resulting json object.

  CommandException:
    type: object
    properties:
      json:
        type: string
        description: The return code and error output.

