swagger: "2.0"

info:
	title: Camera API Endpoint
	version: "1.0"

basePath: /api/camera
x-swagger-router-controller: src.api.camera


paths:
	/dslr-camera/on:
		get:
			summary: Turns the dslr camera on.
			operationId: dslr_camera.on

	/dslr-camera/off:
		get:
			summary: Turns the dslr camera off.
			operationId: dslr_camera.off

	/dslr-camera/status:
		get:
			summary: Retrieves a summary of the DSLR's status.
			operationId: dslr_camera.status

	/video-camera/on:
		get:
			summary: Turns the video camera on.
			operationId: video_camera.on

	/video-camera/off:
		get:
			summary: Turns the video camera off.
			operationId: video_camera.off

	/picture/{date}:
		get:
			summary: Retrieve pictures taken on the date specified.
			operationId: picture.date

	/picture/{id}:
		get:
			summary: Download a picture by its id.
			operationId: picture.id

	/thumbnail/{id}:
		get:
			summary: Download a thumbnail by the pictures id.
			operationId: thumbnail.get

		delete:
			summary: Delete a thumbnail by the pictures id.
			operationId: thumbnail.delete
