swagger: "2.0"

info:
  title: Config File API Endpoint
  version: "1.0"

basePath: /api/configfile

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header


paths:
  /check:
    get:
      summary: Checks that the config file in use is valid.
      operationId: src.api.configfile.endpoints.check
      responses:
        200:
          description: Config file is valid.
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'

  /whitelist:
    get:
      summary: Gets the config files whitelist (editable entries).
      operationId: src.api.configfile.endpoints.whitelist
      responses:
        200:
          description: Config file whitelist.
          schema:
            $ref: '#/definitions/Json'
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'

  /config:
    get:
      summary: Gets the config file.
      operationId: src.api.configfile.endpoints.getConfig
      responses:
        200:
          description: Config file.
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'

    put:
      summary: Updates a config file entry.
      operationId: src.api.configfile.endpoints.updateConfig
      parameters:
        - name: row_item
          in: body
          schema:
            type: array
            items:
              type: string
      responses:
        204:
          description: Config file entry successfully updated.
        500:
          description: Failure while running command.
          schema:
            $ref: '#/definitions/CommandException'


definitions:
  Json:
    type: object
    properties:
      json:
        type: string
        description: Resulting json object.

  CommandException:
    type: object
    properties:
      json:
        type: string
        description: The return code and error output.

